name: integration-test
on:
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [labeled]

permissions:
  contents: read
  issues: read
  pull-requests: read
  statuses: write

jobs:
  integration-test-static:
    runs-on: macos-14
    if: >-
      github.event.issue.pull_request && (
        github.event.comment.body == '/integration-test' ||
        github.event.comment.body == '/integration-test static' ||
        github.event.comment.body == '/integration-test all' ||
        contains(github.event.pull_request.labels.*.name, 'test:integration')
      )
    steps:
      - name: Checkout PR
        uses: trinhngocthuyen/gh-actions/gh/pr/comment/checkout@main
        id: pr_checkout
      - name: Install languages
        uses: trinhngocthuyen/gh-actions/mono/install@main
        with:
          checkout: false
          ruby-version: '3.0'
      - name: Exec
        uses: trinhngocthuyen/gh-actions/gh/pr/with_check@main
        with:
          sha: ${{ steps.pr_checkout.outputs.head_sha }}
          exec: make ci.install ex.test.static

  integration-test-dynamic:
    runs-on: macos-14
    if: >-
      github.event.issue.pull_request && (
        github.event.comment.body == '/integration-test dynamic' ||
        github.event.comment.body == '/integration-test all'
      )
    steps:
      - name: Checkout PR
        uses: trinhngocthuyen/gh-actions/gh/pr/comment/checkout@main
        id: pr_checkout
      - name: Install languages
        uses: trinhngocthuyen/gh-actions/mono/install@main
        with:
          checkout: false
          ruby-version: '3.0'
      - name: Exec
        uses: trinhngocthuyen/gh-actions/gh/pr/with_check@main
        with:
          sha: ${{ steps.pr_checkout.outputs.head_sha }}
          exec: make ci.install ex.test.dynamic
